In [1]:
import torch

In [2]:
x = torch.arange(12, dtype=torch.float32)

In [3]:
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
x.numel()

12

In [5]:
x.shape

torch.Size([12])

In [12]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [7]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [9]:
torch.randn(3, 4)

tensor([[ 0.5419, -0.5326,  0.2587,  0.5201],
        [-1.4272,  1.8072,  0.3853,  0.6540],
        [ 0.1272,  2.0213, -0.0238, -0.4225]])

In [10]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [13]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [14]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [15]:
X[1, 2]

tensor(6.)

In [16]:
torch.exp(x)

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04])

In [17]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

In [18]:
x+y

tensor([ 3.,  4.,  6., 10.])

In [19]:
x-y

tensor([-1.,  0.,  2.,  6.])

In [20]:
x*y

tensor([ 2.,  4.,  8., 16.])

In [21]:
x/y

tensor([0.5000, 1.0000, 2.0000, 4.0000])

In [22]:
x**y

tensor([ 1.,  4., 16., 64.])

In [23]:
x == y

tensor([False,  True, False, False])

In [24]:
x != y

tensor([ True, False,  True,  True])

In [25]:
torch.cat((x, y), dim=0)

tensor([1., 2., 4., 8., 2., 2., 2., 2.])

In [26]:
x.sum()

tensor(15.)

In [27]:
y.sum()

tensor(8)

In [28]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [29]:
A = X.numpy()

In [30]:
B = torch.from_numpy(A)

In [31]:
type(A)

numpy.ndarray

In [32]:
type(B)

torch.Tensor

In [33]:
x < y

tensor([ True, False, False, False])

In [34]:
x > y

tensor([False, False,  True,  True])